<a href="https://colab.research.google.com/github/shashank-github1/git-test/blob/master/facies_prediction_using_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I have used Knn algorithm to classify the type of facies based on the log readings.

In [0]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

We have now upladed all the libraries and modules required.

In [0]:
df= pd.read_csv("facies.csv",index_col=0)

We have read the sample data file

In [277]:
df.head()

GR  ILD_log10  ...  FaciesLabel         FaciesDescription
Depth                     ...                                       
2793.0  77.45      0.664  ...         FSiS  Nonmarine fine siltstone
2793.5  78.26      0.661  ...         FSiS  Nonmarine fine siltstone
2794.0  79.05      0.658  ...         FSiS  Nonmarine fine siltstone
2794.5  86.10      0.655  ...         FSiS  Nonmarine fine siltstone
2795.0  74.58      0.647  ...         FSiS  Nonmarine fine siltstone

[5 rows x 9 columns]

In [0]:
def func1(x):
  if x== "Nonmarine fine siltstone":
    return 0
  elif x== "Nonmarine course siltstone":
    return 1
  elif x== "Packstone-grainstone":
    return 2
  elif x== "Wackestone":
    return 3
  elif x== "Dolomite":
    return 4
  elif x== "Marine siltstone and shale":
    return 5
  elif x== "Mudstone":
    return 6
  elif x== "Phylloid-algal bafflestone":
    return 7
  elif x== "Nonmarine sandstone":
    return 8
  else:
    return 9


Since, the target was given in string, I found it best to convert it to integer values for measurement. I used a basic python function for it.

In [0]:
df['target']= df["FaciesDescription"].apply(func1)

Here, I have added a new column- 'target' in the dataframe. I used apply function for this.

In [280]:
df.tail()

GR  ILD_log10  DeltaPHI  ...  FaciesLabel  FaciesDescription  target
Depth                                ...                                        
3120.5  46.719      0.947     1.828  ...           MS           Mudstone       6
3121.0  44.563      0.953     2.241  ...           MS           Mudstone       6
3121.5  49.719      0.964     2.925  ...           MS           Mudstone       6
3122.0  51.469      0.965     3.083  ...           MS           Mudstone       6
3122.5  50.031      0.970     2.609  ...           MS           Mudstone       6

[5 rows x 10 columns]

In [0]:
zero_not_accepted= ['PE']
for column in zero_not_accepted:
  mean=int(df[column].mean(skipna=True))
  df[column]= df[column].replace(np.NaN,mean)

This step is very important since it replaces the null values with the mean of the rest of the values in that column. Only, the column 'PE' has null values.

In [0]:
df2= df.drop(['WellName','FaciesLabel','FaciesDescription'],axis= 1)

These columns contain string values so they are dropped cause there is no use now as we have already converted facies description into integer values.

In [283]:
df2.head()

GR  ILD_log10  DeltaPHI   PHIND   PE  Facies  target
Depth                                                          
2793.0  77.45      0.664       9.9  11.915  4.6       3       0
2793.5  78.26      0.661      14.2  12.565  4.1       3       0
2794.0  79.05      0.658      14.8  13.050  3.6       3       0
2794.5  86.10      0.655      13.9  13.115  3.5       3       0
2795.0  74.58      0.647      13.5  13.300  3.4       3       0

In [0]:
X= df2.iloc[:, 0:6]
Y= df2.iloc[:, 6]
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, random_state=0, test_size=0.2)

80% of data is used fro training and 20% for testing.

In [0]:
sc_X= StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

Scaling is very important for knn algorithm because ultimately we deal with the closeness of the neighbours based on the distance between them

In [286]:
import math
math.sqrt(len(Y_test))

28.809720581775867

Hence we Identify k as 27

In [0]:
classifier = KNeighborsClassifier(n_neighbors=27, p= 10, metric='minkowski')

In [288]:
classifier.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=27, p=10,
                     weights='uniform')

In [289]:
Y_pred= classifier.predict(X_test)
Y_pred

array([2, 7, 8, 3, 2, 1, 8, 3, 3, 8, 1, 3, 2, 0, 2, 3, 3, 1, 2, 1, 0, 2,
       2, 6, 3, 1, 0, 1, 3, 5, 6, 3, 8, 8, 3, 1, 0, 0, 3, 2, 5, 0, 7, 2,
       2, 1, 2, 3, 2, 1, 0, 0, 8, 0, 1, 1, 0, 2, 7, 1, 3, 3, 3, 2, 5, 1,
       2, 2, 2, 1, 2, 0, 1, 2, 3, 2, 2, 1, 0, 7, 7, 2, 0, 0, 3, 0, 8, 2,
       1, 3, 6, 3, 2, 0, 2, 2, 1, 6, 1, 1, 4, 2, 3, 5, 3, 0, 0, 5, 0, 0,
       2, 2, 3, 1, 1, 3, 5, 2, 7, 2, 3, 5, 2, 4, 2, 3, 7, 2, 1, 2, 2, 3,
       1, 8, 2, 1, 4, 2, 3, 8, 0, 0, 4, 2, 8, 2, 6, 2, 1, 0, 5, 1, 1, 2,
       3, 5, 3, 5, 1, 2, 3, 6, 1, 2, 0, 1, 7, 1, 0, 1, 4, 1, 6, 7, 2, 8,
       8, 8, 2, 6, 1, 2, 4, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1, 0, 3, 3, 5,
       4, 2, 2, 2, 8, 5, 2, 1, 1, 1, 3, 1, 3, 5, 0, 6, 2, 3, 5, 6, 1, 0,
       3, 0, 2, 7, 1, 1, 0, 0, 7, 3, 1, 3, 5, 2, 1, 1, 0, 1, 7, 8, 4, 2,
       1, 0, 1, 3, 7, 1, 8, 1, 6, 8, 0, 0, 7, 1, 2, 3, 3, 3, 5, 5, 2, 5,
       6, 0, 7, 3, 4, 1, 1, 2, 2, 2, 3, 1, 3, 1, 2, 3, 1, 1, 6, 3, 3, 2,
       3, 2, 3, 5, 3, 0, 1, 1, 0, 4, 0, 3, 1, 0, 1,

In [290]:
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
print(f1_score(Y_test, Y_pred, average='micro'))

[[105  35   0   0   0   1   1   0   0]
 [ 32 155   0   0   0   0   0   0   0]
 [  0   0 124   8   1   1   0  11   0]
 [  0   0   8  95   5   6   9   0   0]
 [  2   0  11   5  11   2   2   0   0]
 [ 17   0   0   1   0  31  10   0   0]
 [  2   0   0  30   0  11  12   0   0]
 [  0   0   8   0   3   0   0  21   0]
 [  1  21   0   0   0   0   0   0  32]]
0.7060240963855422
